/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VslRouteImport } from './routes/vsl'
import { Route as Upsell1RouteImport } from './routes/upsell1'
import { Route as IndexRouteImport } from './routes/index'

const VslRoute = VslRouteImport.update({
  id: '/vsl',
  path: '/vsl',
  getParentRoute: () => rootRouteImport,
} as any)
const Upsell1Route = Upsell1RouteImport.update({
  id: '/upsell1',
  path: '/upsell1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/upsell1': typeof Upsell1Route
  '/vsl': typeof VslRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/upsell1': typeof Upsell1Route
  '/vsl': typeof VslRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/upsell1': typeof Upsell1Route
  '/vsl': typeof VslRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/upsell1' | '/vsl'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/upsell1' | '/vsl'
  id: '__root__' | '/' | '/upsell1' | '/vsl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Upsell1Route: typeof Upsell1Route
  VslRoute: typeof VslRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vsl': {
      id: '/vsl'
      path: '/vsl'
      fullPath: '/vsl'
      preLoaderRoute: typeof VslRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell1': {
      id: '/upsell1'
      path: '/upsell1'
      fullPath: '/upsell1'
      preLoaderRoute: typeof Upsell1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Upsell1Route: Upsell1Route,
  VslRoute: VslRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
