/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VslRouteImport } from './routes/vsl'
import { Route as Upsell3RouteImport } from './routes/upsell3'
import { Route as Upsell2RouteImport } from './routes/upsell2'
import { Route as Upsell1RouteImport } from './routes/upsell1'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisclaimersRefundRouteImport } from './routes/disclaimers.refund'
import { Route as DisclaimersFtcRouteImport } from './routes/disclaimers.ftc'
import { Route as DisclaimersEarningsRouteImport } from './routes/disclaimers.earnings'

const VslRoute = VslRouteImport.update({
  id: '/vsl',
  path: '/vsl',
  getParentRoute: () => rootRouteImport,
} as any)
const Upsell3Route = Upsell3RouteImport.update({
  id: '/upsell3',
  path: '/upsell3',
  getParentRoute: () => rootRouteImport,
} as any)
const Upsell2Route = Upsell2RouteImport.update({
  id: '/upsell2',
  path: '/upsell2',
  getParentRoute: () => rootRouteImport,
} as any)
const Upsell1Route = Upsell1RouteImport.update({
  id: '/upsell1',
  path: '/upsell1',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimersRefundRoute = DisclaimersRefundRouteImport.update({
  id: '/disclaimers/refund',
  path: '/disclaimers/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimersFtcRoute = DisclaimersFtcRouteImport.update({
  id: '/disclaimers/ftc',
  path: '/disclaimers/ftc',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimersEarningsRoute = DisclaimersEarningsRouteImport.update({
  id: '/disclaimers/earnings',
  path: '/disclaimers/earnings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/painel': typeof PainelRoute
  '/upsell1': typeof Upsell1Route
  '/upsell2': typeof Upsell2Route
  '/upsell3': typeof Upsell3Route
  '/vsl': typeof VslRoute
  '/disclaimers/earnings': typeof DisclaimersEarningsRoute
  '/disclaimers/ftc': typeof DisclaimersFtcRoute
  '/disclaimers/refund': typeof DisclaimersRefundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/painel': typeof PainelRoute
  '/upsell1': typeof Upsell1Route
  '/upsell2': typeof Upsell2Route
  '/upsell3': typeof Upsell3Route
  '/vsl': typeof VslRoute
  '/disclaimers/earnings': typeof DisclaimersEarningsRoute
  '/disclaimers/ftc': typeof DisclaimersFtcRoute
  '/disclaimers/refund': typeof DisclaimersRefundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/painel': typeof PainelRoute
  '/upsell1': typeof Upsell1Route
  '/upsell2': typeof Upsell2Route
  '/upsell3': typeof Upsell3Route
  '/vsl': typeof VslRoute
  '/disclaimers/earnings': typeof DisclaimersEarningsRoute
  '/disclaimers/ftc': typeof DisclaimersFtcRoute
  '/disclaimers/refund': typeof DisclaimersRefundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/painel'
    | '/upsell1'
    | '/upsell2'
    | '/upsell3'
    | '/vsl'
    | '/disclaimers/earnings'
    | '/disclaimers/ftc'
    | '/disclaimers/refund'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/painel'
    | '/upsell1'
    | '/upsell2'
    | '/upsell3'
    | '/vsl'
    | '/disclaimers/earnings'
    | '/disclaimers/ftc'
    | '/disclaimers/refund'
  id:
    | '__root__'
    | '/'
    | '/painel'
    | '/upsell1'
    | '/upsell2'
    | '/upsell3'
    | '/vsl'
    | '/disclaimers/earnings'
    | '/disclaimers/ftc'
    | '/disclaimers/refund'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelRoute: typeof PainelRoute
  Upsell1Route: typeof Upsell1Route
  Upsell2Route: typeof Upsell2Route
  Upsell3Route: typeof Upsell3Route
  VslRoute: typeof VslRoute
  DisclaimersEarningsRoute: typeof DisclaimersEarningsRoute
  DisclaimersFtcRoute: typeof DisclaimersFtcRoute
  DisclaimersRefundRoute: typeof DisclaimersRefundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vsl': {
      id: '/vsl'
      path: '/vsl'
      fullPath: '/vsl'
      preLoaderRoute: typeof VslRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell3': {
      id: '/upsell3'
      path: '/upsell3'
      fullPath: '/upsell3'
      preLoaderRoute: typeof Upsell3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell2': {
      id: '/upsell2'
      path: '/upsell2'
      fullPath: '/upsell2'
      preLoaderRoute: typeof Upsell2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell1': {
      id: '/upsell1'
      path: '/upsell1'
      fullPath: '/upsell1'
      preLoaderRoute: typeof Upsell1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimers/refund': {
      id: '/disclaimers/refund'
      path: '/disclaimers/refund'
      fullPath: '/disclaimers/refund'
      preLoaderRoute: typeof DisclaimersRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimers/ftc': {
      id: '/disclaimers/ftc'
      path: '/disclaimers/ftc'
      fullPath: '/disclaimers/ftc'
      preLoaderRoute: typeof DisclaimersFtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimers/earnings': {
      id: '/disclaimers/earnings'
      path: '/disclaimers/earnings'
      fullPath: '/disclaimers/earnings'
      preLoaderRoute: typeof DisclaimersEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelRoute: PainelRoute,
  Upsell1Route: Upsell1Route,
  Upsell2Route: Upsell2Route,
  Upsell3Route: Upsell3Route,
  VslRoute: VslRoute,
  DisclaimersEarningsRoute: DisclaimersEarningsRoute,
  DisclaimersFtcRoute: DisclaimersFtcRoute,
  DisclaimersRefundRoute: DisclaimersRefundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
