/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VslRouteImport } from './routes/vsl'
import { Route as Upsell3RouteImport } from './routes/upsell3'
import { Route as Upsell2RouteImport } from './routes/upsell2'
import { Route as Upsell1RouteImport } from './routes/upsell1'
import { Route as IndexRouteImport } from './routes/index'

const VslRoute = VslRouteImport.update({
  id: '/vsl',
  path: '/vsl',
  getParentRoute: () => rootRouteImport,
} as any)
const Upsell3Route = Upsell3RouteImport.update({
  id: '/upsell3',
  path: '/upsell3',
  getParentRoute: () => rootRouteImport,
} as any)
const Upsell2Route = Upsell2RouteImport.update({
  id: '/upsell2',
  path: '/upsell2',
  getParentRoute: () => rootRouteImport,
} as any)
const Upsell1Route = Upsell1RouteImport.update({
  id: '/upsell1',
  path: '/upsell1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/upsell1': typeof Upsell1Route
  '/upsell2': typeof Upsell2Route
  '/upsell3': typeof Upsell3Route
  '/vsl': typeof VslRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/upsell1': typeof Upsell1Route
  '/upsell2': typeof Upsell2Route
  '/upsell3': typeof Upsell3Route
  '/vsl': typeof VslRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/upsell1': typeof Upsell1Route
  '/upsell2': typeof Upsell2Route
  '/upsell3': typeof Upsell3Route
  '/vsl': typeof VslRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/upsell1' | '/upsell2' | '/upsell3' | '/vsl'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/upsell1' | '/upsell2' | '/upsell3' | '/vsl'
  id: '__root__' | '/' | '/upsell1' | '/upsell2' | '/upsell3' | '/vsl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Upsell1Route: typeof Upsell1Route
  Upsell2Route: typeof Upsell2Route
  Upsell3Route: typeof Upsell3Route
  VslRoute: typeof VslRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vsl': {
      id: '/vsl'
      path: '/vsl'
      fullPath: '/vsl'
      preLoaderRoute: typeof VslRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell3': {
      id: '/upsell3'
      path: '/upsell3'
      fullPath: '/upsell3'
      preLoaderRoute: typeof Upsell3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell2': {
      id: '/upsell2'
      path: '/upsell2'
      fullPath: '/upsell2'
      preLoaderRoute: typeof Upsell2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell1': {
      id: '/upsell1'
      path: '/upsell1'
      fullPath: '/upsell1'
      preLoaderRoute: typeof Upsell1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Upsell1Route: Upsell1Route,
  Upsell2Route: Upsell2Route,
  Upsell3Route: Upsell3Route,
  VslRoute: VslRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
